project:
  type: website
  output-dir: docs

website:
  title: "Aprendiendo Ciencia de Datos XD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - breve_analisis_exploratorio.qmd
      - breve_eda_python.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

